# Generated by Django 4.0.2 on 2022-03-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feed',
            table='Feed',
        ),
    ]
