# Generated by Django 4.0.2 on 2022-03-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_feed_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_users',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='chat_users',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='user_id',
            new_name='user',
        ),
    ]
