# Generated by Django 4.0.2 on 2022-03-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_rename_chat_id_chat_users_chat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='feed_id',
            new_name='feed',
        ),
    ]
